# docker-compose com servidor PostgreSQL 
name: FundamentosSQL

services:
  # Servidor 1: PostgreSQL Configuration
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:   # Servidor 1: PostgreSQL


networks:
  default:
    name: FundamentosSQL-network
    #external: true # uncomment this on production
    driver: bridge
