# docker-compose com ferramenta pgAdmin 
name: FundamentosSQL

services:
  # Web Interface for Database: PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      TZ: ${TZ}
    user: "5050:5050"  # Especifica o UID e GID do usuário pgadmin
    networks:
      - default

volumes:
  pgadmin_data:    # Web Interface: pgAdmin


networks:
  default:
    name: FundamentosSQL-network
    #external: true # uncomment this on production
    driver: bridge
