# docker-compose com servidor mysql 
name: FundamentosSQL

services:
  # Servidor 1: MySQL Configuration
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:      # Servidor 1: MySQL

networks:
  default:
    name: FundamentosSQL-network
    #external: true # uncomment this on production
    driver: bridge
