# docker-compose com ferramenta web adminer
name: FundamentosSQL

services:
  # Web Interface for Database: vários
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default

networks:
  default:
    name: FundamentosSQL-network
    #external: true # uncomment this on production
    driver: bridge
