# docker-compose com ferramenta web phpmyadmin
name: SQLab

services:
  # Web Interface for Database: MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_PORT: 3306
      TZ: ${TZ}
    networks:
      - default

networks:
  default:
    name: SQLab-network
    #external: true # uncomment this on production
    driver: bridge
